set(AMBER_SOURCES
    alloc_error.hpp
    linear_allocator.cpp
    linear_allocator.hpp
    linear_allocator.inl
    pool_allocator.cpp
    pool_allocator.hpp
    pool_allocator.inl
    stack_allocator.cpp
    stack_allocator.hpp
    stack_allocator.inl
    util.cpp
    util.hpp
    util.inl
)

prepend_paths(
    "${AMBER_SOURCES}"
    "src/amber"
    "AMBER_SOURCES"
)
