set(AMBER_SOURCES
    aligned_buffer.cpp
    aligned_buffer.hpp
    bitwise_enum.hpp
    concept.hpp
    linear_allocator.cpp
    linear_allocator.hpp
    linear_allocator.inl
    malloc_buffer.cpp
    malloc_buffer.hpp
    mmap_buffer.cpp
    mmap_buffer.hpp
    pool_allocator.cpp
    pool_allocator.hpp
    pool_allocator.inl
    stack_allocator.cpp
    stack_allocator.hpp
    stack_allocator.inl
    util.cpp
    util.hpp
    util.inl
)

prepend_paths(
    "${AMBER_SOURCES}"
    "src/amber"
    "AMBER_SOURCES"
)
