set(AMBER_SOURCES
    except.hpp
    except/alignment_error.cpp
    except/alignment_error.hpp
    except/invalid_allocate_error.cpp
    except/invalid_allocate_error.hpp
    except/out_of_bounds_error.cpp
    except/out_of_bounds_error.hpp
    except/out_of_capacity_error.cpp
    except/out_of_capacity_error.hpp
    linear_allocator.cpp
    linear_allocator.hpp
    linear_allocator.inl
    pool_allocator.cpp
    pool_allocator.hpp
    pool_allocator.inl
    util.cpp
    util.hpp
    util.inl
)

prepend_paths(
    "${AMBER_SOURCES}"
    "src/amber"
    "AMBER_SOURCES"
)
